- name: create dumps folder
  file:
    path: db_dumps
    state: directory

- name: dump DB
  postgresql_db:
    name: "{{ project_name }}"
    state: dump
    target: db_dumps/{{ new_backup_name }}
    # Note: name will be local time of the controller
    target_opts: --format=custom  # same as -Fc
    login_user: "{{ ansible_user }}"
