project_name: minsalud-misuper
server_git_url: git@bitbucket.org:magnet-cl/minsalud-misuper.git
server_root_dir: /home/{{ ansible_user }}/{{ project_name }}
service_name: django-{{ project_name }}.service
development: no
django_port: 8000
ansible_python_interpreter: auto
