- name: deploy
  hosts: all
  pre_tasks:
    - name: import check Ansible version task
      import_tasks: utils/assert-ansible-version.yaml
      tags: always
  roles:
    - update-code
    - role: quickstart
      tags: quickstart
    - server-install
