- name: download DB
  hosts: all
  pre_tasks:
    - name: import check Ansible version task
      import_tasks: utils/assert-ansible-version.yaml
  tasks:
    - name: backup
      include_role:
        name: db
        tasks_from: backup
      when: dump_name is not defined

    - name: download
      include_role:
        name: db
        tasks_from: download
