all:
  hosts:
    localhost:
      ansible_host: localhost
      ansible_connection: local
      server_root_dir: "{{ lookup('env', 'PWD') | dirname }}"
      development: yes
      interactive_path: "{{ lookup('env', 'PATH') }}"

  children:
    remote:   # Group "remote"
      hosts:
        development:
          ansible_host: furia-dev.magnet.cl
          server_domain: furia-dev.magnet.cl
          branch: development

        development_super:
          ansible_host: 30.30.30.33
          server_domain: 30.30.30.33
          branch: development
          ansible_user: admsuper
          ansible_port: 10022

        qa_super:
          ansible_host: 30.30.30.34
          server_domain: 30.30.30.34
          branch: master  # ?
          ansible_user: admsuper
          ansible_port: 10022

      vars:
        ansible_user: magnet
