- name: set archive variable with current time
  set_fact:
    archive_name: "media-{{ '%Y-%m-%d-%H-%M-%S' | strftime(ansible_date_time.epoch) }}.tgz"

- name: archive Media
  archive:
    path: "{{ server_root_dir }}/project/media"
    dest: "{{ archive_name }}"
    # Note: name will have local time of the controller
